### ISSUE TITLE
 _transactionStatus: 'pending' 

### ISSUE THREAD

**Issue by arsen3d** [perak/meteor-bigchain-collection#1]
How long does it take  "_transactionStatus" to be "ok"

**Comment by arsen3d** [comment]
> I20171024-21:51:47.998(-7)? [ { _id: 'f6xvXujaYB4P9mvji',
I20171024-21:51:48.028(-7)?     hello: 'world',
I20171024-21:51:48.029(-7)?     _transactionId: null,
I20171024-21:51:48.029(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.029(-7)?   { _id: 'Sx2JzjMYgpLa8Rk4e',
I20171024-21:51:48.030(-7)?     hello: 'world',
I20171024-21:51:48.030(-7)?     _transactionId: null,
I20171024-21:51:48.031(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.031(-7)?   { _id: 'aNK4RdwPAyczGePbP',
I20171024-21:51:48.032(-7)?     hello: 'world',
I20171024-21:51:48.032(-7)?     _transactionId: null,
I20171024-21:51:48.032(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.033(-7)?   { _id: 'N9DARDoCr8wLcotnF',
I20171024-21:51:48.033(-7)?     hello: 'world',
I20171024-21:51:48.033(-7)?     _transactionId: null,
I20171024-21:51:48.033(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.034(-7)?   { _id: 'T8MsCQdkWMGeXaBLv',
I20171024-21:51:48.040(-7)?     hello: 'world',
I20171024-21:51:48.040(-7)?     _transactionId: null,
I20171024-21:51:48.041(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.041(-7)?   { _id: 'BjCJtB7rgxCcMZJuH',
I20171024-21:51:48.041(-7)?     hello: 'world',
I20171024-21:51:48.042(-7)?     _transactionId: null,
I20171024-21:51:48.042(-7)?     _transactionStatus: 'pending' },
I20171024-21:51:48.042(-7)?   { _id: 'cgbHf6TJnD9D8disi',
I20171024-21:51:48.043(-7)?     hello: 'world',
I20171024-21:51:48.043(-7)?     _transactionId: null,
I20171024-21:51:48.043(-7)?     _transactionStatus: 'pending' } ]

**Comment by perak** [comment]
It takes few seconds. Are you connected to bigchaindb? (see your settings.json - it is set by default to local instance of bigchaindb but you can change url to public IPDB)

**Comment by arsen3d** [comment]
{ "bigchain": {
"url": "https://test.ipdb.io:9984/api/v1/",
"publicKey": "removed_key",
"privateKey": "removed_key"
}}

**Comment by paradoxewan** [comment]
having the same issue, not sure where to find the keys for test.ipdb.io can onle seem to find app id and secret

**Comment by arsen3d** [comment]
You can get a free account here: https://developers.ipdb.io/

**Comment by arsen3d** [comment]
Has this only been tested with running bigchaindb locally?

**Comment by perak** [comment]
@arsen3d yes, this is tested only by running bigchaindb locally. By the way, this package is actually my first try playing with bigchaindb, and this approach is wrong by design - for example, if data is entered via another client software (directly via API or whatever) data will nit be visible in your application. Maybe I can implement “sync” (listen bigchain’s websicket for confirmed transaction and add into local mongo collection new transactions) but this is still “suspicious” design because data is as secure as your meteor app’s mongo database (and we will have duplicate data - one in bigchain another in loca mongo) and performance is questionable.

By the way, 3 weeks ago I was in Berlin 2 days at workshop with BigchainDB guys, and now my eyes are “open” and I am preparing better way to access BDB from meteor applicaton.

**Comment by perak** [comment]
However, I can add feature to access IPDB via this package, but I cannot promise when ‘cause I got heavy workload these days, but maybe you can try (simply add appId) - I am open for pull requests :)

**Comment by arsen3d** [comment]
resolved in my pull request.

**Comment by arsen3d** [comment]
I'd like to know how to get livequery with bigchaindb. Maybe meteor forums are the place to ask.

**Comment by arsen3d** [comment]
@perak There is another blockchain project called Tendermint. I'd be curious to know if it can be adapted to work with meteor as synchronization datastore.

**Comment by perak** [comment]
@arsen3d interesting one! I started reading docs and I believe it is possible, but I cannot do it due to lack of free time (maybe, if day lasts 30 hours :) ).
